export const LOAD_NEW_BOOKS = 'LOAD_NEW_BOOKS';
export const SET_NEW_BOOKS = 'SET_NEW_BOOKS';

export const LOAD_SEARCH_BOOKS = 'LOAD_SEARCH_BOOKS';
export const SET_SEARCH_BOOKS = 'SET_SEARCH_BOOKS';

export const LOAD_SELECTED_BOOK = 'LOAD_SELECTED_BOOK';
export const SET_SELECTED_BOOK = 'SET_SELECTED_BOOK';

export const SET_FAVORITE_BOOK = 'SET_FAVORITE_BOOK';
export const REMOVE_FAVORITE_BOOK = 'REMOVE_FAVORITE_BOOK';
export const REMOVE_ALL_FAVORITES = 'REMOVE_ALL_FAVORITES';

export const SET_VIEWED_BOOK = 'SET_VIEWED_BOOK';
export const REMOVE_VIEWED_BOOK = 'REMOVE_VIEWED_BOOK';
export const REMOVE_ALL_VIEWED = 'REMOVE_ALL_VIEWED';

export const SET_CART_BOOK = 'SET_CART_BOOK';
export const REMOVE_CART_BOOK = 'REMOVE_CART_BOOK';
export const CLEAR_CART = 'CLEAR_CART';




