export const SET_THEME = 'SET_THEME';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_CART_STATUS = 'SET_CART_STATUS';
export const SET_SEARCH_REQUEST = 'SET_SEARCH_REQUEST';
export const SET_LOADER_STATUS = 'SET_LOADER_STATUS';
export const SET_PAGINATION_ITEM = 'SET_PAGINATION_ITEM';
export const SET_PROFILE_MODAL_VISIBLE = 'SET_PROFILE_MODAL_VISIBLE';
export const SET_SIGN_IN_MODAL_VISIBLE = 'SET_SIGN_IN_MODAL_VISIBLE';
export const SET_REGISTRATION_MODAL_VISIBLE = 'SET_REGISTRATION_MODAL_VISIBLE';
export const SET_ACTIVATION_MODAL_VISIBLE = 'SET_ACTIVATION_MODAL_VISIBLE';
export const SET_SUCCESS_MODAL_VISIBLE = 'SET_SUCCESS_MODAL_VISIBLE';
export const SET_LOADER_VISIBLE = 'SET_LOADER_VISIBLE';
export const SET_SEARCH_STATUS = 'SET_SEARCH_STATUS';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SET_SORT_PARAM = 'SET_SORT_PARAM';
export const SET_ERROR_VISIBLE = 'SET_ERROR_VISIBLE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_404 = 'SET_404';
export const SET_ACTION_MODAL = 'SET_ACTION_MODAL';







